### ISSUE TITLE
consensus.py fails to write output file

### ISSUE THREAD

**Issue by bharat1912** [lbobay/CoreCruncher#5]
I. Ran the following successfully with the proteins in the example file:
$python corecruncher_master.py -in example -out out_folder1 -ext .prot -align muscle -ref Serratia_oryzae_J11-6.prot -score 60 
AND
$python corecruncher_master.py -in example -out out_folder2 -ext .prot -align muscle -ref Serratia_grimesii_A2.prot -score 60 

II. However, the consensus.py on the above two folders failed.
$python consensus.py -folders out_folder1 out_folder2 -in example/ -out /media/bharat/volume1/Folder_consensus

(2, ' folders will be analyzed:', ['out_folder1/', 'out_folder2/'])
('Core genome of ', 'out_folder2/', 1973)
('Core genome of ', 'out_folder1/', 1996)
(77, 1919)
(1915, 4)
('partial=', 1996)
['out_folder1/']
out_folder2/
('new genes', 54)
('CONSENSUS CORE GENOME:', 2050)
('Writing output file consensus_core.txt in ', '/media/bharat/volume1/Folder_consensus/')
Traceback (most recent call last):
  File "consensus.py", line 313, in <module>
    f=open(outpath + "consensus_core.txt","w")
IOError: [Errno 2] No such file or directory: '/media/bharat/volume1/Folder_consensus/consensus_core.txt'

Assistance to resolve this error appreciated.

Thanks
Bharat

**Comment by lbobay** [comment]
It looks like a path issue. Have you checked that the path is working and that you have permission to write in it?On Sep 3, 2023, at 06:03, bharat1912 ***@***.***> wrote:﻿
I. Ran the following successfully with the proteins in the example file:
$python corecruncher_master.py -in example -out out_folder1 -ext .prot -align muscle -ref Serratia_oryzae_J11-6.prot -score 60
AND
$python corecruncher_master.py -in example -out out_folder2 -ext .prot -align muscle -ref Serratia_grimesii_A2.prot -score 60
II. However, the consensus.py on the above two folders failed.
$python consensus.py -folders out_folder1 out_folder2 -in example/ -out /media/bharat/volume1/Folder_consensus
(2, ' folders will be analyzed:', ['out_folder1/', 'out_folder2/'])
('Core genome of ', 'out_folder2/', 1973)
('Core genome of ', 'out_folder1/', 1996)
(77, 1919)
(1915, 4)
('partial=', 1996)
['out_folder1/']
out_folder2/
('new genes', 54)
('CONSENSUS CORE GENOME:', 2050)
('Writing output file consensus_core.txt in ', '/media/bharat/volume1/Folder_consensus/')
Traceback (most recent call last):
File "consensus.py", line 313, in 
f=open(outpath + "consensus_core.txt","w")
IOError: [Errno 2] No such file or directory: '/media/bharat/volume1/Folder_consensus/consensus_core.txt'
Assistance to resolve this error appreciated.
Thanks
Bharat
